version: 0.2

phases:
  pre_build:
    commands:
      - $(aws ecr get-login --no-include-email --region eu-west-1)
  build:
    commands:
      - docker build -t nnapp:$IMAGE_TAG ./
      - docker tag nnapp:$IMAGE_TAG 297541991551.dkr.ecr.eu-west-1.amazonaws.com/nnapp:$IMAGE_TAG
  post_build:
    commands:
      - docker push 297541991551.dkr.ecr.eu-west-1.amazonaws.com/nnapp:$IMAGE_TAG
