version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region eu-west-1)
  pre_build:
    commands:
      - echo Pre_Build started on `date`
      - echo Running tests
      # - python setup.py test
      - docker run --rm -ti -v ./:/app/app01 -w /app/app01 python:3.6 python setup.py test
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t nnapp:$IMAGE_TAG ./
      - docker tag nnapp:$IMAGE_TAG 297541991551.dkr.ecr.eu-west-1.amazonaws.com/nnapp:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 297541991551.dkr.ecr.eu-west-1.amazonaws.com/nnapp:$IMAGE_TAG
